spring.profiles.active=dev

#image service
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
cloudinary.cloudname =dhoj5fmxr
cloudinary.apikey =${CLOUDINARY_API_KEY}
cloudinary.apisecret =${CLOUDINARY_API_SECRET}


#security
spring.security.user.password=${DEMO_USER_PASSWORD}
spring.security.user.name=user
security.jwt.secret-key =${JWT_SECRET}
